// Generated by CoffeeScript 1.6.3
var docpadConfig,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

docpadConfig = {
  templateData: {
    site: {
      url: "http://iredmedia.com",
      title: "Web Audio DAW",
      description: "A quick demo of the WebAudio API",
      keywords: "music, daw, audio, web-audio, api",
      styles: ['css/style.css', 'css/vendor/normalize.css', 'css/vendor/main.css'],
      scripts: ['//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js', 'js/plugins.js', 'js/BufferLoader.js', 'js/RedAudio.js', 'js/main.js']
    },
    getPreparedTitle: function() {
      if (this.document.title) {
        return "" + this.document.title + " | " + this.site.title;
      } else {
        return this.site.title;
      }
    },
    getPreparedDescription: function() {
      return this.document.description || this.site.description;
    },
    getPreparedKeywords: function() {
      return this.site.keywords.concat(this.document.keywords || []).join(', ');
    }
  },
  events: {
    serverExtend: function(opts) {
      var docpad, latestConfig, newUrl, oldUrls, server;
      server = opts.server;
      docpad = this.docpad;
      latestConfig = docpad.getConfig();
      oldUrls = latestConfig.templateData.site.oldUrls || [];
      newUrl = latestConfig.templateData.site.url;
      return server.use(function(req, res, next) {
        var _ref;
        if (_ref = req.headers.host, __indexOf.call(oldUrls, _ref) >= 0) {
          return res.redirect(newUrl + req.url, 301);
        } else {
          return next();
        }
      });
    }
  }
};

module.exports = docpadConfig;
